export const ActionTypes = {
    SET_LOGGEDIN_USER: "SET_LOGGEDIN_USER",
    SET_TOKEN: "SET_TOKEN",
    IS_AUTHORISZED: "IS_AUTHORIZED",
    SET_LOADER: "SET_LOADER",
    SESSION_TIMEOUT: "SESSION_TIMEOUT"
}