export const ActionTypes = {
    USER_LOGGEDIN: "USER_LOGGEDIN",
    ACCESS_TOKEN: "ACCESS_TOKEN",
    AUTHORIZATION: "AUTHORIZATION",
    LOADER: "LOADER",
    SET_PRODUCTS: "SET_PRODUCTS",
    CLEAR_STORE: "CLEAR_STORE"
}